clear
RED='\033[0;31m'
NC='\033[0m' # No Color (reset)
echo "     ______     ______     ______             "
echo "    /\  __ \   /\  == \   /\  == \            "
echo "    \ \  __ \  \ \  __<   \ \  _-/            "
echo "     \ \_\ \_\  \ \_\ \_\  \ \_\              "
echo "      \/_/\/_/   \/_/ /_/   \/_/              "
echo "                                              "
echo "  ______     ______     ______     __   __    "
echo " /\  ___\   /\  ___\   /\  __ \   /\ "-.\ \   "
echo " \ \___  \  \ \ \____  \ \  __ \  \ \ \-.  \  "
echo "  \/\_____\  \ \_____\  \ \_\ \_\  \ \_\\"\_\ "
echo "   \/_____/   \/_____/   \/_/\/_/   \/_/ \/_/ "
echo "                                              "
echo ""
echo -e "${RED} The creator is not responsible for the use given${NC}"
echo -e "${RED} to the application and its functions.${NC}"
echo ""
echo "In Work..."
echo ""